use_frameworks!

target 'CL_ShanYanSDK_Example' do
  pod 'CL_ShanYanSDK', :path => '../'

  target 'CL_ShanYanSDK_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
